name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: ["address", "leak", "undefined"]

    steps:
    - uses: actions/checkout@v3
    - name: make test
      run: make test
      env:
        CFLAGS: -O0 -fstack-protector-all -D_FORTIFY_SOURCE=2 -fsanitize=${{ matrix.sanitizer }}
    - name: test SHORTEXA
      run: cd test/SHORTEXA && sh test.sh
